---
editor: 
  markdown: 
    wrap: 72
---

# **Kayla's Literature Review**

[Methods to analyze time-to-event data: The cox regression analysis.
Oxidative Medicine and Cellular Longevity,
2021](https://onlinelibrary.wiley.com/doi/10.1155/2021/1302811)

**What is the goal for this paper?**

The goal of this paper is to explain the basic ideas of cox regression
and how it is applied in a particular study. The article explains how to
interpret the outcome of the regression analysis to generate insights.

**Why is it important?**

Cox regression can only be applied once proportional assumption of the
risk is identified. This article explains how to identify proportional
assumption, create a hazard ratio, and interpret the results depending
on the type of risk factor. If the risk factor is binary, the result can
be interpreted as the estimated increase in HR in patients with the risk
factor vs those without If the risk factor is continuous, the HR is
interpreted as an increase/decrease in the hazard rate of death due to a
1 unit increase in the variable.

**How is it solved? - methods**

The article gives several examples in clinical research of how cox
regression is applied, these examples are calculating the hazard ratio
of specific groups of people with specific genetic problems or markers.
An example is a study that was conducted to assess the effect of gamma
glutamyl transferase (GGT) on the risk of all-cause morality in Italian
people over 65 who are free from liver disease.

**Results/limitations, if any.**

The limitations of this regression analysis is largely based on the
prerequisite of proportional hazards. Additionally, the number of
covariates tested with this method must account for the number of
patients with the event of interest.

[The analysis of survival data in nephrology: basic concepts and methods
of Cox regression, Kidney
International](https://www.kidney-international.org/article/S0085-2538(15)53407-8/fulltext)

**What is the goal for this paper?**

The purpose of this paper is to explain the concepts of the Cox
regression technique, what proportionality assumption means, and how to
interpret the results.

**Why is it important?**

There are different interpretations based on whether the regression
model is univariate or has confounding variables. Based on which
covariates are being used, the impact on the outcome of survival may
change.

**How is it solved? - methods**

The first example shows Cox regression analysis with a single binary
covariate, diabetes. Zero is used for non-diabetic and one is used for
diabetics. This analysis gives us a hazard Ratio (HR) of 1.711 which
tells us the mortality of diabetics is higher than non-diabetics.

The analysis is rerun adding in the confounding effect of age, using
multiple cox regression. The results show the hazard ratio on diabetes
is 1.939, which means age has an even stronger impact on the mortality
of diabetics than the first model.

**Results/limitations, if any.**

The same limitations are mentioned here; if the survival curves of the
variables cross, we do not meet the assumption of proportionality and
extensions to the Cox model are needed.

[Analyzing time to event outcomes with a Cox regression model. WIREs
Comp Stat](https://wires.onlinelibrary.wiley.com/doi/10.1002/wics.1197)

**What is the goal of this paper?**

This article summarizes the concepts of Cox regression and how to
interpret the results of the analyses.

**Why is it important?**

This article explains the concept of censored survival times and their
meaning within the Cox regression technique. There will always be a
number of patients that are not effected by the events of interest and
are alive at the end of study and follow-up period. In these cases, the
period of observation is cut off before the event of interest, and the
survival times are termed as censored.

**How is it solved? - methods**

In this study, researchers were interpreting the data from a trial on
patients with malignant melanoma. The results show that sex does not
significantly effect the survival rate between patients, even though the
baseline group sees a 9% decrease in the risk of death.

**Results/limitations, if any.**

There is a family of fully parametric models that accommodate
multiplicative effects of explanatory variables on survival times,
meaning they do not meet assumptions of proportionality.

[Time-varying covariates and coefficients in Cox regression models. Ann
Transl Med.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6015946/)

**What is the goal of this paper?**

This article explains how to carry out Cox regression with time-varying
covariates in R.

**Why is it important?**

Time-varying covariates do not meet the proportionality assumptions, so
a different analysis is needed.

**How is it solved? - methods**

Time-dependent Cox models are used for this analysis. First a Cox model
must be fit using the coxph() function in R. The results can be used in
a generic plot() function to identify turning points in the data. Once
turning points are identified, we can use a step function to split the
analysis time into intervals using the survSplit() function. This
function creates a new variable tgroup, which identifies which time
interval each row belongs to in the stratified results. The timecox()
function is an additional method that can be used for time-fixed or
time-varying coefficients.

**Results/limitations, if any.**

This article describes some but not all methods that can be used when
using time-varying coefficients. The model fit may be improved by using
derived variables from longitudinal measurements.

[riskRegression: Predicting the risk of an event using Cox regression
models. / Ozenne, Brice; Sørensen, Anne Lyngholm; Scheike, Thomas et al.
In: The R Journal](https://journal.r-project.org/articles/RJ-2017-062/)

**What is the goal of this paper?**

This article introduces the riskRegression package in R and details how
to implement this package to interpret the absolute risk of a covariate
when competing risks are presents.

**Why is it important?**

Risk regression package allows more than 2 competing risks: Estimate
cause-specific hazards using csc() function The output is a class “Cause
Specific Cox” which will be used to compute absolute risk Next step is
to call predict() method to construct confidence intervals and
confidence bands for absolute risks.

newdata \<- data.frame(age = c(45,67), logthick = c(0.1,0.2), epicel =
c("present","not present"), sex = c("Female","Male"))

pfit1 \<- predict(cfit1, newdata = newdata, cause = 1, times =
c(867,3500))

To obtain confidence intervals set se argument to TRUE Use autoplot()
for predicted risk across time

[Tutorial: Survival Estimation for Cox Regression Models with
Time-Varying Coefficients Using SAS and R. Journal of Statistical
Software](https://www.jstatsoft.org/article/view/v061c01)

**What is the goal of this paper?**

To illustrate survival estimation for the time-varying coefficient
model, using SAS and R,

**How is it solved? - methods**

Data preparation starts with coxph() which separates one observation per
subject into separate time intervals

-   data = R data frame that identifies the single-record-per-patient
    data set that we want to expand into the counting process style.

-   cut = numeric vector of unique event times.

-   end = character string corresponding to the variable name for time
    of event or censoring in data. This will become the variable
    representing the end, or stop time, of each time interval in the
    counting process style.

-   event = character string corresponding to the name of the binary
    variable that indicates events in data. It is important that this
    variable takes a value of 1 for events and 0 otherwise

First we must define a vector of unique time events

R\> cut.points \<- unique(SURV$time[SURV$death == 1\]) Use newdata
option in survfit to provide the desired covariate values in the data
frame

In order to obtain predictions from this time-varying model, we create a
data set with the intervals between event times and another for
covariate values at which we want predictions.

R\> last \<- rossi2$id[which.max(rossi2$week)\] R\> intervals \<-
rossi2\[rossi2\$id == last, c("week0", "week", "arrest")\] R\> covs \<-
data.frame(rbind(cbind(rossi\[c("age", "prio")\], fin = 0), +
cbind(rossi\[c("age", "prio")\], fin = 1)))

**Results/Limitations, if any.**

It is important to differentiate between clinical significance and
statistical significance. For example, a statistically significant
violation of proportional hazards may be identified, when really the
practical significance of the violation is very minor. Survival
estimates guide researchers when evaluating if statistical differences
translate to practical differences.
